apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-user
  labels:
    app: my-app-user
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-user
  template:
    metadata:
      labels:
        app: my-app-user
    spec:
      containers:
      - image: ademolaadeolu18/user-api   
        name: user-api
        ports:
        - containerPort: 8080
     


