apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  POSTGRES_USERNAME: oluwatobi
  POSTGRES_PASSWORD: September30
  POSTGRES_HOST: tobgramdb.cjqxyto4p9i5.us-east-2.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: test-292558888762-dev
  AWS_REGION: us-east-2
  AWS_PROFILE: default
  JWT_SECRET: hello
  URL: http://localhost:8100